# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'Ios_ass4' do
  use_frameworks!
  pod 'MJRefresh'
  pod 'Alamofire'
  pod 'SDWebImage'

  # Pods for Ios_ass4

end
